### ISSUE TITLE
bug(#2): Email/Password Auth Issues

### ISSUE THREAD

**Issue by ThunderDoesDev** [LinkCordApp/Issues#2]
Once press Continue, it dosen't redirect to dashboard, nothing happens.
Gif below.
https://cdn.thunderdoesdev.gg/images/vwain.gif

**Comment by TheRealToxicDev** [comment]
> Once press Continue, it dosen't redirect to dashboard, nothing happens. Gif below. https://cdn.thunderdoesdev.gg/images/vwain.gif

If you are on a Desktop Browser please provide a console log while you attempt the request as stated here: 
```shell
**Browser Users  (please provide the following):**
1. Right click on the page and select the `Inspect Element` or `Inspect` option.
2. In the "Dev Tools" menu that opens up select the `Console` tab at the top.
3. Proceed to do what you are experiencing issues with while this console is open and provide us with any errors that arise.
```

**Comment by ThunderDoesDev** [comment]
https://cdn.thunderdoesdev.gg/images/skl42.png

**Comment by ThunderDoesDev** [comment]
That’s only errors I’m getting atm.

**Comment by TheRealToxicDev** [comment]
Was able to reproduce this issue after creating a new account. We will look into a fix 👌🏻

**Comment by TheRealToxicDev** [comment]
Removed for the time being. See latest changes. 👌🏻
