### ISSUE TITLE
bug(#3) Github Auth Failure

### ISSUE THREAD

**Issue by Miya25** [LinkCordApp/Issues#3]
so when you login with github it say redirecting to dashboard but it not redirect it will be on login page only or i can say "stuck" on login page

**Comment by RizonFTW** [comment]
Can you take a screenshot with the console please? So, we can look into it further.

**Comment by Miya25** [comment]
![image](https://user-images.githubusercontent.com/87431619/166131397-9c88e24f-f1c7-4389-88ab-e1bb6ee6073f.png)
![image](https://user-images.githubusercontent.com/87431619/166131401-63e18ca7-7d58-4ec0-a993-bd61baf0de62.png)
not the pop up is gone.. and it won't even take me to the dashboard

**Comment by TheRealToxicDev** [comment]
> ![image](https://user-images.githubusercontent.com/87431619/166131397-9c88e24f-f1c7-4389-88ab-e1bb6ee6073f.png)
> ![image](https://user-images.githubusercontent.com/87431619/166131401-63e18ca7-7d58-4ec0-a993-bd61baf0de62.png)
> not the pop up is gone.. and it won't even take me to the dashboard

Please show us the errors in console when you try to log in. If you need to please google how to open the dev tools console on your  browser. 👌🏻

**Comment by Miya25** [comment]
![image](https://user-images.githubusercontent.com/87431619/166142630-5b0a8c5e-9e61-4ab4-8236-af046580f295.png)

**Comment by TheRealToxicDev** [comment]
GitHub auth has been removed for the time being.
