### ISSUE TITLE
new(bug): Can't Log in

### ISSUE THREAD

**Issue by HinaseDev** [LinkCordApp/Issues#5]
**Describe the bug**
The Authentication on the Roadmap Site fails due to it being not in the valid callbacks, apparently

**To Reproduce**
1. Go to 'https://roadmap.linkcord.bio/'
2. Click on 'Log in'
3. See error

**Expected behavior**
I expected the Authentication Window to appear

**Screenshots**
![image](https://user-images.githubusercontent.com/112501342/233479164-5d64bdd7-4278-40fa-a5a1-8af6f58b741d.png)

**Desktop Browser Users (please provide the following):**
```
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 
The resource at “https://linkcord.bio/ShortBio.webp” was blocked due to its Cross-Origin-Resource-Policy header (or lack thereof). See https://developer.mozilla.org/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)
```
**Additional context**
...

**Comment by RizonFTW** [comment]
Hi there, thank you for reporting this.

I'll take a look into it and will provide where possible.

**Comment by TheRealToxicDev** [comment]
@RizonFTW @HinaseDev Issue has been resolcved! 👍🏻
