### ISSUE TITLE
new(bug): UI Nav glitch

### ISSUE THREAD

**Issue by Miya25** [LinkCordApp/Issues#6]
**Describe the bug**
The NavBar UI act bit weird
**To Reproduce**
Steps to reproduce the behaviour:
1. Tap on your avatar after that the dropdown will open showing the nav issue

**Expected behaviour**
the nav bar will expand
**Screenshots**
here is a video demonstrating the issue https://cordx.lol/users/787241442770419722/6mAmwkFF.mp4

**Desktop Browser Users (please provide the following):**
any console thingy is not required for this issue in my knowledge

**Comment by TheRealToxicDev** [comment]
Not a glitch 🤷

**Comment by Miya25** [comment]
huh?
